language: node_js
node_js:
- "10"
stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
cache:
  directories:
    - node_modules

install:
  - npm install -g serverless

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: 
        - npm install
        - npm test
    - stage: deploy
      name: "Deploy to AWS"
      script: sls deploy -v