language: node_js
node_js:
- "10"
cache:
  directories:
    - node_modules

install:
  - npm install -g serverless

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: 
        - npm install
        - npm test
    - stage: deploy
      name: "Deploy to AWS"
      script: sls deploy -v
      if: branch = master